// Copyright 2025 PT Espay Debit Indonesia Koe
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package merchant_management

/*
Merchant Management API

API for merchant management operations in DANA

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


import (
	"encoding/json"
	"bytes"
	"fmt"
	utils "github.com/dana-id/dana-go/utils"
)

// checks if the CreateShopResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &CreateShopResponse{}

// CreateShopResponse struct for CreateShopResponse
type CreateShopResponse struct {
	Response CreateShopResponseResponse `json:"response"`
}

type _CreateShopResponse CreateShopResponse

// NewCreateShopResponse instantiates a new CreateShopResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateShopResponse(response CreateShopResponseResponse) *CreateShopResponse {
	this := CreateShopResponse{}
	this.Response = response
	return &this
}

// NewCreateShopResponseWithDefaults instantiates a new CreateShopResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateShopResponseWithDefaults() *CreateShopResponse {
	this := CreateShopResponse{}
	return &this
}

// GetResponse returns the Response field value
func (o *CreateShopResponse) GetResponse() CreateShopResponseResponse {
	if o == nil {
		var ret CreateShopResponseResponse
		return ret
	}

	return o.Response
}

// GetResponseOk returns a tuple with the Response field value
// and a boolean to check if the value has been set.
func (o *CreateShopResponse) GetResponseOk() (*CreateShopResponseResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Response, true
}

// SetResponse sets field value
func (o *CreateShopResponse) SetResponse(v CreateShopResponseResponse) {
	o.Response = v
}

func (o CreateShopResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateShopResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["response"] = o.Response
	return toSerialize, nil
}

func (o *CreateShopResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"response",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateShopResponse := _CreateShopResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateShopResponse)

	if err != nil {
		return err
	}

	*o = CreateShopResponse(varCreateShopResponse)

	return err
}

type NullableCreateShopResponse struct {
	value *CreateShopResponse
	isSet bool
}

func (v NullableCreateShopResponse) Get() *CreateShopResponse {
	return v.value
}

func (v *NullableCreateShopResponse) Set(val *CreateShopResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateShopResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateShopResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateShopResponse(val *CreateShopResponse) *NullableCreateShopResponse {
	return &NullableCreateShopResponse{value: val, isSet: true}
}

func (v NullableCreateShopResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateShopResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


