// Copyright 2025 PT Espay Debit Indonesia Koe
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package merchant_management

/*
Merchant Management API

API for merchant management operations in DANA

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


import (
	"encoding/json"
	"bytes"
	"fmt"
	utils "github.com/dana-id/dana-go/utils"
)

// checks if the QueryShopResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &QueryShopResponse{}

// QueryShopResponse struct for QueryShopResponse
type QueryShopResponse struct {
	Response QueryShopResponseResponse `json:"response"`
	// Signature
	Signature *string `json:"signature,omitempty"`
}

type _QueryShopResponse QueryShopResponse

// NewQueryShopResponse instantiates a new QueryShopResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryShopResponse(response QueryShopResponseResponse) *QueryShopResponse {
	this := QueryShopResponse{}
	this.Response = response
	return &this
}

// NewQueryShopResponseWithDefaults instantiates a new QueryShopResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryShopResponseWithDefaults() *QueryShopResponse {
	this := QueryShopResponse{}
	return &this
}

// GetResponse returns the Response field value
func (o *QueryShopResponse) GetResponse() QueryShopResponseResponse {
	if o == nil {
		var ret QueryShopResponseResponse
		return ret
	}

	return o.Response
}

// GetResponseOk returns a tuple with the Response field value
// and a boolean to check if the value has been set.
func (o *QueryShopResponse) GetResponseOk() (*QueryShopResponseResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Response, true
}

// SetResponse sets field value
func (o *QueryShopResponse) SetResponse(v QueryShopResponseResponse) {
	o.Response = v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *QueryShopResponse) GetSignature() string {
	if o == nil || utils.IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryShopResponse) GetSignatureOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *QueryShopResponse) HasSignature() bool {
	if o != nil && !utils.IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *QueryShopResponse) SetSignature(v string) {
	o.Signature = &v
}

func (o QueryShopResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryShopResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["response"] = o.Response
	if !utils.IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	return toSerialize, nil
}

func (o *QueryShopResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"response",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryShopResponse := _QueryShopResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryShopResponse)

	if err != nil {
		return err
	}

	*o = QueryShopResponse(varQueryShopResponse)

	return err
}

type NullableQueryShopResponse struct {
	value *QueryShopResponse
	isSet bool
}

func (v NullableQueryShopResponse) Get() *QueryShopResponse {
	return v.value
}

func (v *NullableQueryShopResponse) Set(val *QueryShopResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryShopResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryShopResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryShopResponse(val *QueryShopResponse) *NullableQueryShopResponse {
	return &NullableQueryShopResponse{value: val, isSet: true}
}

func (v NullableQueryShopResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryShopResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


