// Copyright 2025 PT Espay Debit Indonesia Koe
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package merchant_management

/*
Merchant Management API

API for merchant management operations in DANA

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


import (
	"encoding/json"
	"bytes"
	"fmt"
	utils "github.com/dana-id/dana-go/utils"
)

// checks if the QueryMerchantResourceRequest type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &QueryMerchantResourceRequest{}

// QueryMerchantResourceRequest struct for QueryMerchantResourceRequest
type QueryMerchantResourceRequest struct {
	// This is a merchantId of DANA
	RequestMerchantId string `json:"requestMerchantId"`
	// This is a constant merchant resource info request, currently available for value of constant these: MERCHANT_DEPOSIT_BALANCE MERCHANT_AVAILABLE_BALANCE MERCHANT_TOTAL_BALANCE value for this request can't be empty or wrong constant info 
	MerchantResourceInfoList []string `json:"merchantResourceInfoList"`
}

type _QueryMerchantResourceRequest QueryMerchantResourceRequest

// NewQueryMerchantResourceRequest instantiates a new QueryMerchantResourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryMerchantResourceRequest(requestMerchantId string, merchantResourceInfoList []string) *QueryMerchantResourceRequest {
	this := QueryMerchantResourceRequest{}
	this.RequestMerchantId = requestMerchantId
	this.MerchantResourceInfoList = merchantResourceInfoList
	return &this
}

// NewQueryMerchantResourceRequestWithDefaults instantiates a new QueryMerchantResourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryMerchantResourceRequestWithDefaults() *QueryMerchantResourceRequest {
	this := QueryMerchantResourceRequest{}
	return &this
}

// GetRequestMerchantId returns the RequestMerchantId field value
func (o *QueryMerchantResourceRequest) GetRequestMerchantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestMerchantId
}

// GetRequestMerchantIdOk returns a tuple with the RequestMerchantId field value
// and a boolean to check if the value has been set.
func (o *QueryMerchantResourceRequest) GetRequestMerchantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestMerchantId, true
}

// SetRequestMerchantId sets field value
func (o *QueryMerchantResourceRequest) SetRequestMerchantId(v string) {
	o.RequestMerchantId = v
}

// GetMerchantResourceInfoList returns the MerchantResourceInfoList field value
func (o *QueryMerchantResourceRequest) GetMerchantResourceInfoList() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.MerchantResourceInfoList
}

// GetMerchantResourceInfoListOk returns a tuple with the MerchantResourceInfoList field value
// and a boolean to check if the value has been set.
func (o *QueryMerchantResourceRequest) GetMerchantResourceInfoListOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MerchantResourceInfoList, true
}

// SetMerchantResourceInfoList sets field value
func (o *QueryMerchantResourceRequest) SetMerchantResourceInfoList(v []string) {
	o.MerchantResourceInfoList = v
}

func (o QueryMerchantResourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryMerchantResourceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestMerchantId"] = o.RequestMerchantId
	toSerialize["merchantResourceInfoList"] = o.MerchantResourceInfoList
	return toSerialize, nil
}

func (o *QueryMerchantResourceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestMerchantId",
		"merchantResourceInfoList",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryMerchantResourceRequest := _QueryMerchantResourceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryMerchantResourceRequest)

	if err != nil {
		return err
	}

	*o = QueryMerchantResourceRequest(varQueryMerchantResourceRequest)

	return err
}

type NullableQueryMerchantResourceRequest struct {
	value *QueryMerchantResourceRequest
	isSet bool
}

func (v NullableQueryMerchantResourceRequest) Get() *QueryMerchantResourceRequest {
	return v.value
}

func (v *NullableQueryMerchantResourceRequest) Set(val *QueryMerchantResourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryMerchantResourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryMerchantResourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryMerchantResourceRequest(val *QueryMerchantResourceRequest) *NullableQueryMerchantResourceRequest {
	return &NullableQueryMerchantResourceRequest{value: val, isSet: true}
}

func (v NullableQueryMerchantResourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryMerchantResourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


