// Copyright 2025 PT Espay Debit Indonesia Koe
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package widget

// Code generated by generate-enum.sh; DO NOT EDIT.

type ServiceType string
const (
    SERVICETYPE_PARKING_ ServiceType = "PARKING"
    SERVICETYPE_INVESTMENT_ ServiceType = "INVESTMENT"
)

type ServiceScenario string
const (
    SERVICESCENARIO_SCAN_AND_PAY_ ServiceScenario = "SCAN_AND_PAY"
    SERVICESCENARIO_EXIT_AND_PAY_ ServiceScenario = "EXIT_AND_PAY"
    SERVICESCENARIO_EMAS_PURCHASE_ ServiceScenario = "EMAS_PURCHASE"
)

type PromoType string
const (
    PROMOTYPE_CASH_BACK_ PromoType = "CASH_BACK"
    PROMOTYPE_DISCOUNT_ PromoType = "DISCOUNT"
    PROMOTYPE_VOUCHER_ PromoType = "VOUCHER"
    PROMOTYPE_POINT_ PromoType = "POINT"
)

type AcquirementStatus string
const (
    ACQUIREMENTSTATUS_INIT_ AcquirementStatus = "INIT"
    ACQUIREMENTSTATUS_SUCCESS_ AcquirementStatus = "SUCCESS"
    ACQUIREMENTSTATUS_CLOSED_ AcquirementStatus = "CLOSED"
    ACQUIREMENTSTATUS_PAYING_ AcquirementStatus = "PAYING"
    ACQUIREMENTSTATUS_MERCHANT_ACCEPT_ AcquirementStatus = "MERCHANT_ACCEPT"
    ACQUIREMENTSTATUS_CANCELLED_ AcquirementStatus = "CANCELLED"
)

type Mode string
const (
    MODE_API_ Mode = "API"
    MODE_DEEPLINK_ Mode = "DEEPLINK"
)

type ResourceType string
const (
    RESOURCETYPE_BALANCE_ ResourceType = "BALANCE"
    RESOURCETYPE_TRANSACTION_URL_ ResourceType = "TRANSACTION_URL"
    RESOURCETYPE_MASK_DANA_ID_ ResourceType = "MASK_DANA_ID"
    RESOURCETYPE_TOPUP_URL_ ResourceType = "TOPUP_URL"
    RESOURCETYPE_OTT_ ResourceType = "OTT"
    RESOURCETYPE_USER_KYC_ ResourceType = "USER_KYC"
)

type ResultStatus string
const (
    RESULTSTATUS_S_ ResultStatus = "S"
    RESULTSTATUS_F_ ResultStatus = "F"
    RESULTSTATUS_U_ ResultStatus = "U"
)

type SourcePlatform string
const (
    SOURCEPLATFORM_IPG_ SourcePlatform = "IPG"
)

type TerminalType string
const (
    TERMINALTYPE_APP_ TerminalType = "APP"
    TERMINALTYPE_WEB_ TerminalType = "WEB"
    TERMINALTYPE_WAP_ TerminalType = "WAP"
    TERMINALTYPE_SYSTEM_ TerminalType = "SYSTEM"
)

type OrderTerminalType string
const (
    ORDERTERMINALTYPE_APP_ OrderTerminalType = "APP"
    ORDERTERMINALTYPE_WEB_ OrderTerminalType = "WEB"
    ORDERTERMINALTYPE_WAP_ OrderTerminalType = "WAP"
    ORDERTERMINALTYPE_SYSTEM_ OrderTerminalType = "SYSTEM"
)

type PayMethod string
const (
    PAYMETHOD_BALANCE_ PayMethod = "BALANCE"
    PAYMETHOD_COUPON_ PayMethod = "COUPON"
    PAYMETHOD_NET_BANKING_ PayMethod = "NET_BANKING"
    PAYMETHOD_CREDIT_CARD_ PayMethod = "CREDIT_CARD"
    PAYMETHOD_DEBIT_CARD_ PayMethod = "DEBIT_CARD"
    PAYMETHOD_VIRTUAL_ACCOUNT_ PayMethod = "VIRTUAL_ACCOUNT"
    PAYMETHOD_OTC_ PayMethod = "OTC"
    PAYMETHOD_DIRECT_DEBIT_CREDIT_CARD_ PayMethod = "DIRECT_DEBIT_CREDIT_CARD"
    PAYMETHOD_DIRECT_DEBIT_DEBIT_CARD_ PayMethod = "DIRECT_DEBIT_DEBIT_CARD"
    PAYMETHOD_ONLINE_CREDIT_ PayMethod = "ONLINE_CREDIT"
    PAYMETHOD_LOAN_CREDIT_ PayMethod = "LOAN_CREDIT"
    PAYMETHOD_NETWORK_PAY_ PayMethod = "NETWORK_PAY"
    PAYMETHOD_CARD_ PayMethod = "CARD"
)

type PayOption string
const (
    PAYOPTION_NETWORK_PAY_PG_SPAY_ PayOption = "NETWORK_PAY_PG_SPAY"
    PAYOPTION_NETWORK_PAY_PG_OVO_ PayOption = "NETWORK_PAY_PG_OVO"
    PAYOPTION_NETWORK_PAY_PG_GOPAY_ PayOption = "NETWORK_PAY_PG_GOPAY"
    PAYOPTION_NETWORK_PAY_PG_LINKAJA_ PayOption = "NETWORK_PAY_PG_LINKAJA"
    PAYOPTION_NETWORK_PAY_PG_CARD_ PayOption = "NETWORK_PAY_PG_CARD"
    PAYOPTION_VIRTUAL_ACCOUNT_BCA_ PayOption = "VIRTUAL_ACCOUNT_BCA"
    PAYOPTION_VIRTUAL_ACCOUNT_BNI_ PayOption = "VIRTUAL_ACCOUNT_BNI"
    PAYOPTION_VIRTUAL_ACCOUNT_MANDIRI_ PayOption = "VIRTUAL_ACCOUNT_MANDIRI"
    PAYOPTION_VIRTUAL_ACCOUNT_BRI_ PayOption = "VIRTUAL_ACCOUNT_BRI"
    PAYOPTION_VIRTUAL_ACCOUNT_BTPN_ PayOption = "VIRTUAL_ACCOUNT_BTPN"
    PAYOPTION_VIRTUAL_ACCOUNT_CIMB_ PayOption = "VIRTUAL_ACCOUNT_CIMB"
    PAYOPTION_VIRTUAL_ACCOUNT_PERMATA_ PayOption = "VIRTUAL_ACCOUNT_PERMATA"
)

type Type string
const (
    TYPE_PAY_RETURN_ Type = "PAY_RETURN"
    TYPE_NOTIFICATION_ Type = "NOTIFICATION"
)

