// Copyright 2025 PT Espay Debit Indonesia Koe
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package widget

/*
Widget API

API for enabling the user to make payment from merchant's platform with redirecting to DANA's platform.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


import (
	"encoding/json"
	"bytes"
	"fmt"
	utils "github.com/dana-id/dana-go/utils"
)

// checks if the QueryUserProfileResponseResponse type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &QueryUserProfileResponseResponse{}

// QueryUserProfileResponseResponse struct for QueryUserProfileResponseResponse
type QueryUserProfileResponseResponse struct {
	Head QueryUserProfileResponseResponseHead `json:"head"`
	Body QueryUserProfileResponseResponseBody `json:"body"`
}

type _QueryUserProfileResponseResponse QueryUserProfileResponseResponse

// NewQueryUserProfileResponseResponse instantiates a new QueryUserProfileResponseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryUserProfileResponseResponse(head QueryUserProfileResponseResponseHead, body QueryUserProfileResponseResponseBody) *QueryUserProfileResponseResponse {
	this := QueryUserProfileResponseResponse{}
	this.Head = head
	this.Body = body
	return &this
}

// NewQueryUserProfileResponseResponseWithDefaults instantiates a new QueryUserProfileResponseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryUserProfileResponseResponseWithDefaults() *QueryUserProfileResponseResponse {
	this := QueryUserProfileResponseResponse{}
	return &this
}

// GetHead returns the Head field value
func (o *QueryUserProfileResponseResponse) GetHead() QueryUserProfileResponseResponseHead {
	if o == nil {
		var ret QueryUserProfileResponseResponseHead
		return ret
	}

	return o.Head
}

// GetHeadOk returns a tuple with the Head field value
// and a boolean to check if the value has been set.
func (o *QueryUserProfileResponseResponse) GetHeadOk() (*QueryUserProfileResponseResponseHead, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Head, true
}

// SetHead sets field value
func (o *QueryUserProfileResponseResponse) SetHead(v QueryUserProfileResponseResponseHead) {
	o.Head = v
}

// GetBody returns the Body field value
func (o *QueryUserProfileResponseResponse) GetBody() QueryUserProfileResponseResponseBody {
	if o == nil {
		var ret QueryUserProfileResponseResponseBody
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *QueryUserProfileResponseResponse) GetBodyOk() (*QueryUserProfileResponseResponseBody, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *QueryUserProfileResponseResponse) SetBody(v QueryUserProfileResponseResponseBody) {
	o.Body = v
}

func (o QueryUserProfileResponseResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryUserProfileResponseResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["head"] = o.Head
	toSerialize["body"] = o.Body
	return toSerialize, nil
}

func (o *QueryUserProfileResponseResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"head",
		"body",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryUserProfileResponseResponse := _QueryUserProfileResponseResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryUserProfileResponseResponse)

	if err != nil {
		return err
	}

	*o = QueryUserProfileResponseResponse(varQueryUserProfileResponseResponse)

	return err
}

type NullableQueryUserProfileResponseResponse struct {
	value *QueryUserProfileResponseResponse
	isSet bool
}

func (v NullableQueryUserProfileResponseResponse) Get() *QueryUserProfileResponseResponse {
	return v.value
}

func (v *NullableQueryUserProfileResponseResponse) Set(val *QueryUserProfileResponseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryUserProfileResponseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryUserProfileResponseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryUserProfileResponseResponse(val *QueryUserProfileResponseResponse) *NullableQueryUserProfileResponseResponse {
	return &NullableQueryUserProfileResponseResponse{value: val, isSet: true}
}

func (v NullableQueryUserProfileResponseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryUserProfileResponseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


