/*
Payment Gateway API

API for doing operations in DANA Payment Gateway (Gapura)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payment_gateway

import (
	"encoding/json"
	utils "github.com/dana-id/go_client/utils"
)

// checks if the QueryPaymentRequestAdditionalInfo type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &QueryPaymentRequestAdditionalInfo{}

// QueryPaymentRequestAdditionalInfo Additional information
type QueryPaymentRequestAdditionalInfo struct {
	// Additional information of business scenario
	BusinessScenario *string `json:"businessScenario,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _QueryPaymentRequestAdditionalInfo QueryPaymentRequestAdditionalInfo

// NewQueryPaymentRequestAdditionalInfo instantiates a new QueryPaymentRequestAdditionalInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryPaymentRequestAdditionalInfo() *QueryPaymentRequestAdditionalInfo {
	this := QueryPaymentRequestAdditionalInfo{}
	return &this
}

// NewQueryPaymentRequestAdditionalInfoWithDefaults instantiates a new QueryPaymentRequestAdditionalInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryPaymentRequestAdditionalInfoWithDefaults() *QueryPaymentRequestAdditionalInfo {
	this := QueryPaymentRequestAdditionalInfo{}
	return &this
}

// GetBusinessScenario returns the BusinessScenario field value if set, zero value otherwise.
func (o *QueryPaymentRequestAdditionalInfo) GetBusinessScenario() string {
	if o == nil || utils.IsNil(o.BusinessScenario) {
		var ret string
		return ret
	}
	return *o.BusinessScenario
}

// GetBusinessScenarioOk returns a tuple with the BusinessScenario field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryPaymentRequestAdditionalInfo) GetBusinessScenarioOk() (*string, bool) {
	if o == nil || utils.IsNil(o.BusinessScenario) {
		return nil, false
	}
	return o.BusinessScenario, true
}

// HasBusinessScenario returns a boolean if a field has been set.
func (o *QueryPaymentRequestAdditionalInfo) HasBusinessScenario() bool {
	if o != nil && !utils.IsNil(o.BusinessScenario) {
		return true
	}

	return false
}

// SetBusinessScenario gets a reference to the given string and assigns it to the BusinessScenario field.
func (o *QueryPaymentRequestAdditionalInfo) SetBusinessScenario(v string) {
	o.BusinessScenario = &v
}

func (o QueryPaymentRequestAdditionalInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryPaymentRequestAdditionalInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.BusinessScenario) {
		toSerialize["businessScenario"] = o.BusinessScenario
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QueryPaymentRequestAdditionalInfo) UnmarshalJSON(data []byte) (err error) {
	varQueryPaymentRequestAdditionalInfo := _QueryPaymentRequestAdditionalInfo{}

	err = json.Unmarshal(data, &varQueryPaymentRequestAdditionalInfo)

	if err != nil {
		return err
	}

	*o = QueryPaymentRequestAdditionalInfo(varQueryPaymentRequestAdditionalInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "businessScenario")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQueryPaymentRequestAdditionalInfo struct {
	value *QueryPaymentRequestAdditionalInfo
	isSet bool
}

func (v NullableQueryPaymentRequestAdditionalInfo) Get() *QueryPaymentRequestAdditionalInfo {
	return v.value
}

func (v *NullableQueryPaymentRequestAdditionalInfo) Set(val *QueryPaymentRequestAdditionalInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryPaymentRequestAdditionalInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryPaymentRequestAdditionalInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryPaymentRequestAdditionalInfo(val *QueryPaymentRequestAdditionalInfo) *NullableQueryPaymentRequestAdditionalInfo {
	return &NullableQueryPaymentRequestAdditionalInfo{value: val, isSet: true}
}

func (v NullableQueryPaymentRequestAdditionalInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryPaymentRequestAdditionalInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


