// Copyright 2025 PT Espay Debit Indonesia Koe
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package payment_gateway

/*
Payment Gateway API

API for doing operations in DANA Payment Gateway (Gapura)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


import (
	"encoding/json"
	"bytes"
	"fmt"
	utils "github.com/dana-id/dana-go/utils"
)

// checks if the CreateOrderByRedirectAdditionalInfo type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &CreateOrderByRedirectAdditionalInfo{}

// CreateOrderByRedirectAdditionalInfo struct for CreateOrderByRedirectAdditionalInfo
type CreateOrderByRedirectAdditionalInfo struct {
	// Additional information of merchant category code. This parameter is used to identify the type of business in which a merchant is engaged. Refer to Details of https://dashboard.dana.id/api-docs/read/197#OpenAPI-MerchantCategoryCode
	Mcc string `json:"mcc"`
	// Additional information of extend such as partner passthrough and risk information
	ExtendInfo *string `json:"extendInfo,omitempty"`
	// Additional information of environment info
	EnvInfo EnvInfo `json:"envInfo"`
	// Additional information of order
	Order *OrderRedirectObject `json:"order,omitempty"`
}

type _CreateOrderByRedirectAdditionalInfo CreateOrderByRedirectAdditionalInfo

// NewCreateOrderByRedirectAdditionalInfo instantiates a new CreateOrderByRedirectAdditionalInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderByRedirectAdditionalInfo(mcc string, envInfo EnvInfo) *CreateOrderByRedirectAdditionalInfo {
	this := CreateOrderByRedirectAdditionalInfo{}
	this.Mcc = mcc
	this.EnvInfo = envInfo
	return &this
}

// NewCreateOrderByRedirectAdditionalInfoWithDefaults instantiates a new CreateOrderByRedirectAdditionalInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderByRedirectAdditionalInfoWithDefaults() *CreateOrderByRedirectAdditionalInfo {
	this := CreateOrderByRedirectAdditionalInfo{}
	return &this
}

// GetMcc returns the Mcc field value
func (o *CreateOrderByRedirectAdditionalInfo) GetMcc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mcc
}

// GetMccOk returns a tuple with the Mcc field value
// and a boolean to check if the value has been set.
func (o *CreateOrderByRedirectAdditionalInfo) GetMccOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mcc, true
}

// SetMcc sets field value
func (o *CreateOrderByRedirectAdditionalInfo) SetMcc(v string) {
	o.Mcc = v
}

// GetExtendInfo returns the ExtendInfo field value if set, zero value otherwise.
func (o *CreateOrderByRedirectAdditionalInfo) GetExtendInfo() string {
	if o == nil || utils.IsNil(o.ExtendInfo) {
		var ret string
		return ret
	}
	return *o.ExtendInfo
}

// GetExtendInfoOk returns a tuple with the ExtendInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderByRedirectAdditionalInfo) GetExtendInfoOk() (*string, bool) {
	if o == nil || utils.IsNil(o.ExtendInfo) {
		return nil, false
	}
	return o.ExtendInfo, true
}

// HasExtendInfo returns a boolean if a field has been set.
func (o *CreateOrderByRedirectAdditionalInfo) HasExtendInfo() bool {
	if o != nil && !utils.IsNil(o.ExtendInfo) {
		return true
	}

	return false
}

// SetExtendInfo gets a reference to the given string and assigns it to the ExtendInfo field.
func (o *CreateOrderByRedirectAdditionalInfo) SetExtendInfo(v string) {
	o.ExtendInfo = &v
}

// GetEnvInfo returns the EnvInfo field value
func (o *CreateOrderByRedirectAdditionalInfo) GetEnvInfo() EnvInfo {
	if o == nil {
		var ret EnvInfo
		return ret
	}

	return o.EnvInfo
}

// GetEnvInfoOk returns a tuple with the EnvInfo field value
// and a boolean to check if the value has been set.
func (o *CreateOrderByRedirectAdditionalInfo) GetEnvInfoOk() (*EnvInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvInfo, true
}

// SetEnvInfo sets field value
func (o *CreateOrderByRedirectAdditionalInfo) SetEnvInfo(v EnvInfo) {
	o.EnvInfo = v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *CreateOrderByRedirectAdditionalInfo) GetOrder() OrderRedirectObject {
	if o == nil || utils.IsNil(o.Order) {
		var ret OrderRedirectObject
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderByRedirectAdditionalInfo) GetOrderOk() (*OrderRedirectObject, bool) {
	if o == nil || utils.IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *CreateOrderByRedirectAdditionalInfo) HasOrder() bool {
	if o != nil && !utils.IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given OrderRedirectObject and assigns it to the Order field.
func (o *CreateOrderByRedirectAdditionalInfo) SetOrder(v OrderRedirectObject) {
	o.Order = &v
}

func (o CreateOrderByRedirectAdditionalInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrderByRedirectAdditionalInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mcc"] = o.Mcc
	if !utils.IsNil(o.ExtendInfo) {
		toSerialize["extendInfo"] = o.ExtendInfo
	}
	toSerialize["envInfo"] = o.EnvInfo
	if !utils.IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	return toSerialize, nil
}

func (o *CreateOrderByRedirectAdditionalInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mcc",
		"envInfo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrderByRedirectAdditionalInfo := _CreateOrderByRedirectAdditionalInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrderByRedirectAdditionalInfo)

	if err != nil {
		return err
	}

	*o = CreateOrderByRedirectAdditionalInfo(varCreateOrderByRedirectAdditionalInfo)

	return err
}

type NullableCreateOrderByRedirectAdditionalInfo struct {
	value *CreateOrderByRedirectAdditionalInfo
	isSet bool
}

func (v NullableCreateOrderByRedirectAdditionalInfo) Get() *CreateOrderByRedirectAdditionalInfo {
	return v.value
}

func (v *NullableCreateOrderByRedirectAdditionalInfo) Set(val *CreateOrderByRedirectAdditionalInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderByRedirectAdditionalInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderByRedirectAdditionalInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderByRedirectAdditionalInfo(val *CreateOrderByRedirectAdditionalInfo) *NullableCreateOrderByRedirectAdditionalInfo {
	return &NullableCreateOrderByRedirectAdditionalInfo{value: val, isSet: true}
}

func (v NullableCreateOrderByRedirectAdditionalInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderByRedirectAdditionalInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


