/*
Payment Gateway API

API for doing operations in DANA Payment Gateway (Gapura)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payment_gateway

import (
	"encoding/json"
	"bytes"
	"fmt"
	utils "github.com/dana-id/dana-go-api-client/utils"
)

// checks if the FinishNotify type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &FinishNotify{}

// FinishNotify struct for FinishNotify
type FinishNotify struct {
	// Original transaction identifier on DANA system
	OriginalPartnerReferenceNo string `json:"originalPartnerReferenceNo"`
	// Original transaction identifier on partner system
	OriginalReferenceNo string `json:"originalReferenceNo"`
	// Original external identifier on header message
	OriginalExternalId *string `json:"originalExternalId,omitempty"`
	// Unique identifier for each merchant
	MerchantId string `json:"merchantId"`
	// Sub merchant identifier
	SubMerchantId *string `json:"subMerchantId,omitempty"`
	Amount Money `json:"amount"`
	// Transaction status code:<br> - 00 = Success<br> - 05 = Cancelled (expired)<br> 
	LatestTransactionStatus string `json:"latestTransactionStatus"`
	// Description of transaction status
	TransactionStatusDesc *string `json:"transactionStatusDesc,omitempty"`
	// Transaction creation time (GMT+7, Jakarta)
	CreatedTime string `json:"createdTime" validate:"regexp=^\\\\d{4}-\\\\d{2}-\\\\d{2}T\\\\d{2}:\\\\d{2}:\\\\d{2}\\\\+07:00$"`
	// Transaction completion time (GMT+7, Jakarta)
	FinishedTime string `json:"finishedTime" validate:"regexp=^\\\\d{4}-\\\\d{2}-\\\\d{2}T\\\\d{2}:\\\\d{2}:\\\\d{2}\\\\+07:00$"`
	// Store identifier
	ExternalStoreId *string `json:"externalStoreId,omitempty"`
	AdditionalInfo *FinishNotifyAdditionalInfo `json:"additionalInfo,omitempty"`
}

type _FinishNotify FinishNotify

// NewFinishNotify instantiates a new FinishNotify object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinishNotify(originalPartnerReferenceNo string, originalReferenceNo string, merchantId string, amount Money, latestTransactionStatus string, createdTime string, finishedTime string) *FinishNotify {
	this := FinishNotify{}
	this.OriginalPartnerReferenceNo = originalPartnerReferenceNo
	this.OriginalReferenceNo = originalReferenceNo
	this.MerchantId = merchantId
	this.Amount = amount
	this.LatestTransactionStatus = latestTransactionStatus
	this.CreatedTime = createdTime
	this.FinishedTime = finishedTime
	return &this
}

// NewFinishNotifyWithDefaults instantiates a new FinishNotify object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFinishNotifyWithDefaults() *FinishNotify {
	this := FinishNotify{}
	return &this
}

// GetOriginalPartnerReferenceNo returns the OriginalPartnerReferenceNo field value
func (o *FinishNotify) GetOriginalPartnerReferenceNo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OriginalPartnerReferenceNo
}

// GetOriginalPartnerReferenceNoOk returns a tuple with the OriginalPartnerReferenceNo field value
// and a boolean to check if the value has been set.
func (o *FinishNotify) GetOriginalPartnerReferenceNoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginalPartnerReferenceNo, true
}

// SetOriginalPartnerReferenceNo sets field value
func (o *FinishNotify) SetOriginalPartnerReferenceNo(v string) {
	o.OriginalPartnerReferenceNo = v
}

// GetOriginalReferenceNo returns the OriginalReferenceNo field value
func (o *FinishNotify) GetOriginalReferenceNo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OriginalReferenceNo
}

// GetOriginalReferenceNoOk returns a tuple with the OriginalReferenceNo field value
// and a boolean to check if the value has been set.
func (o *FinishNotify) GetOriginalReferenceNoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginalReferenceNo, true
}

// SetOriginalReferenceNo sets field value
func (o *FinishNotify) SetOriginalReferenceNo(v string) {
	o.OriginalReferenceNo = v
}

// GetOriginalExternalId returns the OriginalExternalId field value if set, zero value otherwise.
func (o *FinishNotify) GetOriginalExternalId() string {
	if o == nil || utils.IsNil(o.OriginalExternalId) {
		var ret string
		return ret
	}
	return *o.OriginalExternalId
}

// GetOriginalExternalIdOk returns a tuple with the OriginalExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinishNotify) GetOriginalExternalIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.OriginalExternalId) {
		return nil, false
	}
	return o.OriginalExternalId, true
}

// HasOriginalExternalId returns a boolean if a field has been set.
func (o *FinishNotify) HasOriginalExternalId() bool {
	if o != nil && !utils.IsNil(o.OriginalExternalId) {
		return true
	}

	return false
}

// SetOriginalExternalId gets a reference to the given string and assigns it to the OriginalExternalId field.
func (o *FinishNotify) SetOriginalExternalId(v string) {
	o.OriginalExternalId = &v
}

// GetMerchantId returns the MerchantId field value
func (o *FinishNotify) GetMerchantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantId
}

// GetMerchantIdOk returns a tuple with the MerchantId field value
// and a boolean to check if the value has been set.
func (o *FinishNotify) GetMerchantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantId, true
}

// SetMerchantId sets field value
func (o *FinishNotify) SetMerchantId(v string) {
	o.MerchantId = v
}

// GetSubMerchantId returns the SubMerchantId field value if set, zero value otherwise.
func (o *FinishNotify) GetSubMerchantId() string {
	if o == nil || utils.IsNil(o.SubMerchantId) {
		var ret string
		return ret
	}
	return *o.SubMerchantId
}

// GetSubMerchantIdOk returns a tuple with the SubMerchantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinishNotify) GetSubMerchantIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.SubMerchantId) {
		return nil, false
	}
	return o.SubMerchantId, true
}

// HasSubMerchantId returns a boolean if a field has been set.
func (o *FinishNotify) HasSubMerchantId() bool {
	if o != nil && !utils.IsNil(o.SubMerchantId) {
		return true
	}

	return false
}

// SetSubMerchantId gets a reference to the given string and assigns it to the SubMerchantId field.
func (o *FinishNotify) SetSubMerchantId(v string) {
	o.SubMerchantId = &v
}

// GetAmount returns the Amount field value
func (o *FinishNotify) GetAmount() Money {
	if o == nil {
		var ret Money
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *FinishNotify) GetAmountOk() (*Money, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *FinishNotify) SetAmount(v Money) {
	o.Amount = v
}

// GetLatestTransactionStatus returns the LatestTransactionStatus field value
func (o *FinishNotify) GetLatestTransactionStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LatestTransactionStatus
}

// GetLatestTransactionStatusOk returns a tuple with the LatestTransactionStatus field value
// and a boolean to check if the value has been set.
func (o *FinishNotify) GetLatestTransactionStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LatestTransactionStatus, true
}

// SetLatestTransactionStatus sets field value
func (o *FinishNotify) SetLatestTransactionStatus(v string) {
	o.LatestTransactionStatus = v
}

// GetTransactionStatusDesc returns the TransactionStatusDesc field value if set, zero value otherwise.
func (o *FinishNotify) GetTransactionStatusDesc() string {
	if o == nil || utils.IsNil(o.TransactionStatusDesc) {
		var ret string
		return ret
	}
	return *o.TransactionStatusDesc
}

// GetTransactionStatusDescOk returns a tuple with the TransactionStatusDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinishNotify) GetTransactionStatusDescOk() (*string, bool) {
	if o == nil || utils.IsNil(o.TransactionStatusDesc) {
		return nil, false
	}
	return o.TransactionStatusDesc, true
}

// HasTransactionStatusDesc returns a boolean if a field has been set.
func (o *FinishNotify) HasTransactionStatusDesc() bool {
	if o != nil && !utils.IsNil(o.TransactionStatusDesc) {
		return true
	}

	return false
}

// SetTransactionStatusDesc gets a reference to the given string and assigns it to the TransactionStatusDesc field.
func (o *FinishNotify) SetTransactionStatusDesc(v string) {
	o.TransactionStatusDesc = &v
}

// GetCreatedTime returns the CreatedTime field value
func (o *FinishNotify) GetCreatedTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *FinishNotify) GetCreatedTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *FinishNotify) SetCreatedTime(v string) {
	o.CreatedTime = v
}

// GetFinishedTime returns the FinishedTime field value
func (o *FinishNotify) GetFinishedTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FinishedTime
}

// GetFinishedTimeOk returns a tuple with the FinishedTime field value
// and a boolean to check if the value has been set.
func (o *FinishNotify) GetFinishedTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FinishedTime, true
}

// SetFinishedTime sets field value
func (o *FinishNotify) SetFinishedTime(v string) {
	o.FinishedTime = v
}

// GetExternalStoreId returns the ExternalStoreId field value if set, zero value otherwise.
func (o *FinishNotify) GetExternalStoreId() string {
	if o == nil || utils.IsNil(o.ExternalStoreId) {
		var ret string
		return ret
	}
	return *o.ExternalStoreId
}

// GetExternalStoreIdOk returns a tuple with the ExternalStoreId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinishNotify) GetExternalStoreIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.ExternalStoreId) {
		return nil, false
	}
	return o.ExternalStoreId, true
}

// HasExternalStoreId returns a boolean if a field has been set.
func (o *FinishNotify) HasExternalStoreId() bool {
	if o != nil && !utils.IsNil(o.ExternalStoreId) {
		return true
	}

	return false
}

// SetExternalStoreId gets a reference to the given string and assigns it to the ExternalStoreId field.
func (o *FinishNotify) SetExternalStoreId(v string) {
	o.ExternalStoreId = &v
}

// GetAdditionalInfo returns the AdditionalInfo field value if set, zero value otherwise.
func (o *FinishNotify) GetAdditionalInfo() FinishNotifyAdditionalInfo {
	if o == nil || utils.IsNil(o.AdditionalInfo) {
		var ret FinishNotifyAdditionalInfo
		return ret
	}
	return *o.AdditionalInfo
}

// GetAdditionalInfoOk returns a tuple with the AdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FinishNotify) GetAdditionalInfoOk() (*FinishNotifyAdditionalInfo, bool) {
	if o == nil || utils.IsNil(o.AdditionalInfo) {
		return nil, false
	}
	return o.AdditionalInfo, true
}

// HasAdditionalInfo returns a boolean if a field has been set.
func (o *FinishNotify) HasAdditionalInfo() bool {
	if o != nil && !utils.IsNil(o.AdditionalInfo) {
		return true
	}

	return false
}

// SetAdditionalInfo gets a reference to the given FinishNotifyAdditionalInfo and assigns it to the AdditionalInfo field.
func (o *FinishNotify) SetAdditionalInfo(v FinishNotifyAdditionalInfo) {
	o.AdditionalInfo = &v
}

func (o FinishNotify) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FinishNotify) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["originalPartnerReferenceNo"] = o.OriginalPartnerReferenceNo
	toSerialize["originalReferenceNo"] = o.OriginalReferenceNo
	if !utils.IsNil(o.OriginalExternalId) {
		toSerialize["originalExternalId"] = o.OriginalExternalId
	}
	toSerialize["merchantId"] = o.MerchantId
	if !utils.IsNil(o.SubMerchantId) {
		toSerialize["subMerchantId"] = o.SubMerchantId
	}
	toSerialize["amount"] = o.Amount
	toSerialize["latestTransactionStatus"] = o.LatestTransactionStatus
	if !utils.IsNil(o.TransactionStatusDesc) {
		toSerialize["transactionStatusDesc"] = o.TransactionStatusDesc
	}
	toSerialize["createdTime"] = o.CreatedTime
	toSerialize["finishedTime"] = o.FinishedTime
	if !utils.IsNil(o.ExternalStoreId) {
		toSerialize["externalStoreId"] = o.ExternalStoreId
	}
	if !utils.IsNil(o.AdditionalInfo) {
		toSerialize["additionalInfo"] = o.AdditionalInfo
	}
	return toSerialize, nil
}

func (o *FinishNotify) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"originalPartnerReferenceNo",
		"originalReferenceNo",
		"merchantId",
		"amount",
		"latestTransactionStatus",
		"createdTime",
		"finishedTime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFinishNotify := _FinishNotify{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFinishNotify)

	if err != nil {
		return err
	}

	*o = FinishNotify(varFinishNotify)

	return err
}

type NullableFinishNotify struct {
	value *FinishNotify
	isSet bool
}

func (v NullableFinishNotify) Get() *FinishNotify {
	return v.value
}

func (v *NullableFinishNotify) Set(val *FinishNotify) {
	v.value = val
	v.isSet = true
}

func (v NullableFinishNotify) IsSet() bool {
	return v.isSet
}

func (v *NullableFinishNotify) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinishNotify(val *FinishNotify) *NullableFinishNotify {
	return &NullableFinishNotify{value: val, isSet: true}
}

func (v NullableFinishNotify) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinishNotify) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


