/*
IPG Cashier Pay API

API for enabling the user to make payment from merchant's platform with redirecting to DANA's platform.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipg

import (
	"encoding/json"
	"bytes"
	"fmt"
	utils "github.com/dana-id/go_client/utils"
)

// checks if the ApplyOTTRequestAdditionalInfo type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ApplyOTTRequestAdditionalInfo{}

// ApplyOTTRequestAdditionalInfo Additional information
type ApplyOTTRequestAdditionalInfo struct {
	// Contains customer token, which has been obtained from binding process
	AccessToken string `json:"accessToken"`
	// IP address of the end user (customer) using IPv4 format
	EndUserIpAddress *string `json:"endUserIpAddress,omitempty"`
	// Device identification on which the API services is currently being accessed by the end user (customer)
	DeviceId string `json:"deviceId"`
	// Location on which the API services is currently being accessed by the end user (customer), refer to ISO 6709 standard representation of geographic point location by coordinates
	Latitude *string `json:"latitude,omitempty" validate:"regexp=^[-+]?[0-9]{1,2}([.][0-9]{1,4})?$"`
	// Location on which the API services is currently being accessed by the end user (customer), refer to ISO 6709 Standard representation of geographic point location by coordinates
	Longitude *string `json:"longitude,omitempty" validate:"regexp=^[-+]?[0-9]{1,2}([.][0-9]{1,4})?$"`
}

type _ApplyOTTRequestAdditionalInfo ApplyOTTRequestAdditionalInfo

// NewApplyOTTRequestAdditionalInfo instantiates a new ApplyOTTRequestAdditionalInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplyOTTRequestAdditionalInfo(accessToken string, deviceId string) *ApplyOTTRequestAdditionalInfo {
	this := ApplyOTTRequestAdditionalInfo{}
	this.AccessToken = accessToken
	this.DeviceId = deviceId
	return &this
}

// NewApplyOTTRequestAdditionalInfoWithDefaults instantiates a new ApplyOTTRequestAdditionalInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplyOTTRequestAdditionalInfoWithDefaults() *ApplyOTTRequestAdditionalInfo {
	this := ApplyOTTRequestAdditionalInfo{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *ApplyOTTRequestAdditionalInfo) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *ApplyOTTRequestAdditionalInfo) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *ApplyOTTRequestAdditionalInfo) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetEndUserIpAddress returns the EndUserIpAddress field value if set, zero value otherwise.
func (o *ApplyOTTRequestAdditionalInfo) GetEndUserIpAddress() string {
	if o == nil || utils.IsNil(o.EndUserIpAddress) {
		var ret string
		return ret
	}
	return *o.EndUserIpAddress
}

// GetEndUserIpAddressOk returns a tuple with the EndUserIpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyOTTRequestAdditionalInfo) GetEndUserIpAddressOk() (*string, bool) {
	if o == nil || utils.IsNil(o.EndUserIpAddress) {
		return nil, false
	}
	return o.EndUserIpAddress, true
}

// HasEndUserIpAddress returns a boolean if a field has been set.
func (o *ApplyOTTRequestAdditionalInfo) HasEndUserIpAddress() bool {
	if o != nil && !utils.IsNil(o.EndUserIpAddress) {
		return true
	}

	return false
}

// SetEndUserIpAddress gets a reference to the given string and assigns it to the EndUserIpAddress field.
func (o *ApplyOTTRequestAdditionalInfo) SetEndUserIpAddress(v string) {
	o.EndUserIpAddress = &v
}

// GetDeviceId returns the DeviceId field value
func (o *ApplyOTTRequestAdditionalInfo) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *ApplyOTTRequestAdditionalInfo) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *ApplyOTTRequestAdditionalInfo) SetDeviceId(v string) {
	o.DeviceId = v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *ApplyOTTRequestAdditionalInfo) GetLatitude() string {
	if o == nil || utils.IsNil(o.Latitude) {
		var ret string
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyOTTRequestAdditionalInfo) GetLatitudeOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *ApplyOTTRequestAdditionalInfo) HasLatitude() bool {
	if o != nil && !utils.IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given string and assigns it to the Latitude field.
func (o *ApplyOTTRequestAdditionalInfo) SetLatitude(v string) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *ApplyOTTRequestAdditionalInfo) GetLongitude() string {
	if o == nil || utils.IsNil(o.Longitude) {
		var ret string
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyOTTRequestAdditionalInfo) GetLongitudeOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *ApplyOTTRequestAdditionalInfo) HasLongitude() bool {
	if o != nil && !utils.IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given string and assigns it to the Longitude field.
func (o *ApplyOTTRequestAdditionalInfo) SetLongitude(v string) {
	o.Longitude = &v
}

func (o ApplyOTTRequestAdditionalInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplyOTTRequestAdditionalInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accessToken"] = o.AccessToken
	if !utils.IsNil(o.EndUserIpAddress) {
		toSerialize["endUserIpAddress"] = o.EndUserIpAddress
	}
	toSerialize["deviceId"] = o.DeviceId
	if !utils.IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !utils.IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	return toSerialize, nil
}

func (o *ApplyOTTRequestAdditionalInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accessToken",
		"deviceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplyOTTRequestAdditionalInfo := _ApplyOTTRequestAdditionalInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplyOTTRequestAdditionalInfo)

	if err != nil {
		return err
	}

	*o = ApplyOTTRequestAdditionalInfo(varApplyOTTRequestAdditionalInfo)

	return err
}

type NullableApplyOTTRequestAdditionalInfo struct {
	value *ApplyOTTRequestAdditionalInfo
	isSet bool
}

func (v NullableApplyOTTRequestAdditionalInfo) Get() *ApplyOTTRequestAdditionalInfo {
	return v.value
}

func (v *NullableApplyOTTRequestAdditionalInfo) Set(val *ApplyOTTRequestAdditionalInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableApplyOTTRequestAdditionalInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableApplyOTTRequestAdditionalInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplyOTTRequestAdditionalInfo(val *ApplyOTTRequestAdditionalInfo) *NullableApplyOTTRequestAdditionalInfo {
	return &NullableApplyOTTRequestAdditionalInfo{value: val, isSet: true}
}

func (v NullableApplyOTTRequestAdditionalInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplyOTTRequestAdditionalInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


