// Copyright 2025 PT Espay Debit Indonesia Koe
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package disbursement

// Code generated by generate-enum.sh; DO NOT EDIT.

type Latesttransactionstatus string
const (
    LATESTTRANSACTIONSTATUS_00_ Latesttransactionstatus = "00"
    LATESTTRANSACTIONSTATUS_01_ Latesttransactionstatus = "01"
    LATESTTRANSACTIONSTATUS_02_ Latesttransactionstatus = "02"
    LATESTTRANSACTIONSTATUS_03_ Latesttransactionstatus = "03"
    LATESTTRANSACTIONSTATUS_04_ Latesttransactionstatus = "04"
    LATESTTRANSACTIONSTATUS_05_ Latesttransactionstatus = "05"
    LATESTTRANSACTIONSTATUS_06_ Latesttransactionstatus = "06"
    LATESTTRANSACTIONSTATUS_07_ Latesttransactionstatus = "07"
)

