// Copyright 2025 PT Espay Debit Indonesia Koe
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package disbursement

/*
Disbursement API

API for doing disbursement operations in DANA, including DANA account inquiry, transfer to DANA, and transfer to bank disbursement

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


import (
	"encoding/json"
	"bytes"
	"fmt"
	utils "github.com/dana-id/dana-go/utils"
)

// checks if the TransferToBankRequestAdditionalInfo type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &TransferToBankRequestAdditionalInfo{}

// TransferToBankRequestAdditionalInfo Additional information
type TransferToBankRequestAdditionalInfo struct {
	// Additional information of withdraw fund type, i.e.<br> MERCHANT_WITHDRAW_FOR_CORPORATE 
	FundType string `json:"fundType"`
	// Additional information of external division identifier. (fundType: MERCHANT_WITHDRAW_FOR_CORPORATE)<br> Notes: The required of this parameter is Optional, but if \"additionalInfo.chargeTarget\" has value DIVISION then the required of this parameter will be changed to Mandatory 
	ExternalDivisionId *string `json:"externalDivisionId,omitempty"`
	// Additional information of charge target. The values are:<br> • null<br> • DIVISION<br> • MERCHANT<br> Notes: If the value is DIVISION, externalDivisionId will be Mandatory 
	ChargeTarget *string `json:"chargeTarget,omitempty"`
	// Additional information of flag result notification on transaction completed (result sync/async)
	NeedNotify *bool `json:"needNotify,omitempty"`
	// Additional information of beneficiary account name for validation purpose
	BeneficiaryAccountName *string `json:"beneficiaryAccountName,omitempty"`
	// Contains customer token, which has been obtained from binding process, refer to Account Binding & Unbinding documentation<br> If request is coming from user interaction, this field is mandatory. If not, just filled customerNumber 
	AccessToken *string `json:"accessToken,omitempty"`
}

type _TransferToBankRequestAdditionalInfo TransferToBankRequestAdditionalInfo

// NewTransferToBankRequestAdditionalInfo instantiates a new TransferToBankRequestAdditionalInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferToBankRequestAdditionalInfo(fundType string) *TransferToBankRequestAdditionalInfo {
	this := TransferToBankRequestAdditionalInfo{}
	this.FundType = fundType
	return &this
}

// NewTransferToBankRequestAdditionalInfoWithDefaults instantiates a new TransferToBankRequestAdditionalInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferToBankRequestAdditionalInfoWithDefaults() *TransferToBankRequestAdditionalInfo {
	this := TransferToBankRequestAdditionalInfo{}
	return &this
}

// GetFundType returns the FundType field value
func (o *TransferToBankRequestAdditionalInfo) GetFundType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FundType
}

// GetFundTypeOk returns a tuple with the FundType field value
// and a boolean to check if the value has been set.
func (o *TransferToBankRequestAdditionalInfo) GetFundTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FundType, true
}

// SetFundType sets field value
func (o *TransferToBankRequestAdditionalInfo) SetFundType(v string) {
	o.FundType = v
}

// GetExternalDivisionId returns the ExternalDivisionId field value if set, zero value otherwise.
func (o *TransferToBankRequestAdditionalInfo) GetExternalDivisionId() string {
	if o == nil || utils.IsNil(o.ExternalDivisionId) {
		var ret string
		return ret
	}
	return *o.ExternalDivisionId
}

// GetExternalDivisionIdOk returns a tuple with the ExternalDivisionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferToBankRequestAdditionalInfo) GetExternalDivisionIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.ExternalDivisionId) {
		return nil, false
	}
	return o.ExternalDivisionId, true
}

// HasExternalDivisionId returns a boolean if a field has been set.
func (o *TransferToBankRequestAdditionalInfo) HasExternalDivisionId() bool {
	if o != nil && !utils.IsNil(o.ExternalDivisionId) {
		return true
	}

	return false
}

// SetExternalDivisionId gets a reference to the given string and assigns it to the ExternalDivisionId field.
func (o *TransferToBankRequestAdditionalInfo) SetExternalDivisionId(v string) {
	o.ExternalDivisionId = &v
}

// GetChargeTarget returns the ChargeTarget field value if set, zero value otherwise.
func (o *TransferToBankRequestAdditionalInfo) GetChargeTarget() string {
	if o == nil || utils.IsNil(o.ChargeTarget) {
		var ret string
		return ret
	}
	return *o.ChargeTarget
}

// GetChargeTargetOk returns a tuple with the ChargeTarget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferToBankRequestAdditionalInfo) GetChargeTargetOk() (*string, bool) {
	if o == nil || utils.IsNil(o.ChargeTarget) {
		return nil, false
	}
	return o.ChargeTarget, true
}

// HasChargeTarget returns a boolean if a field has been set.
func (o *TransferToBankRequestAdditionalInfo) HasChargeTarget() bool {
	if o != nil && !utils.IsNil(o.ChargeTarget) {
		return true
	}

	return false
}

// SetChargeTarget gets a reference to the given string and assigns it to the ChargeTarget field.
func (o *TransferToBankRequestAdditionalInfo) SetChargeTarget(v string) {
	o.ChargeTarget = &v
}

// GetNeedNotify returns the NeedNotify field value if set, zero value otherwise.
func (o *TransferToBankRequestAdditionalInfo) GetNeedNotify() bool {
	if o == nil || utils.IsNil(o.NeedNotify) {
		var ret bool
		return ret
	}
	return *o.NeedNotify
}

// GetNeedNotifyOk returns a tuple with the NeedNotify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferToBankRequestAdditionalInfo) GetNeedNotifyOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.NeedNotify) {
		return nil, false
	}
	return o.NeedNotify, true
}

// HasNeedNotify returns a boolean if a field has been set.
func (o *TransferToBankRequestAdditionalInfo) HasNeedNotify() bool {
	if o != nil && !utils.IsNil(o.NeedNotify) {
		return true
	}

	return false
}

// SetNeedNotify gets a reference to the given bool and assigns it to the NeedNotify field.
func (o *TransferToBankRequestAdditionalInfo) SetNeedNotify(v bool) {
	o.NeedNotify = &v
}

// GetBeneficiaryAccountName returns the BeneficiaryAccountName field value if set, zero value otherwise.
func (o *TransferToBankRequestAdditionalInfo) GetBeneficiaryAccountName() string {
	if o == nil || utils.IsNil(o.BeneficiaryAccountName) {
		var ret string
		return ret
	}
	return *o.BeneficiaryAccountName
}

// GetBeneficiaryAccountNameOk returns a tuple with the BeneficiaryAccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferToBankRequestAdditionalInfo) GetBeneficiaryAccountNameOk() (*string, bool) {
	if o == nil || utils.IsNil(o.BeneficiaryAccountName) {
		return nil, false
	}
	return o.BeneficiaryAccountName, true
}

// HasBeneficiaryAccountName returns a boolean if a field has been set.
func (o *TransferToBankRequestAdditionalInfo) HasBeneficiaryAccountName() bool {
	if o != nil && !utils.IsNil(o.BeneficiaryAccountName) {
		return true
	}

	return false
}

// SetBeneficiaryAccountName gets a reference to the given string and assigns it to the BeneficiaryAccountName field.
func (o *TransferToBankRequestAdditionalInfo) SetBeneficiaryAccountName(v string) {
	o.BeneficiaryAccountName = &v
}

// GetAccessToken returns the AccessToken field value if set, zero value otherwise.
func (o *TransferToBankRequestAdditionalInfo) GetAccessToken() string {
	if o == nil || utils.IsNil(o.AccessToken) {
		var ret string
		return ret
	}
	return *o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferToBankRequestAdditionalInfo) GetAccessTokenOk() (*string, bool) {
	if o == nil || utils.IsNil(o.AccessToken) {
		return nil, false
	}
	return o.AccessToken, true
}

// HasAccessToken returns a boolean if a field has been set.
func (o *TransferToBankRequestAdditionalInfo) HasAccessToken() bool {
	if o != nil && !utils.IsNil(o.AccessToken) {
		return true
	}

	return false
}

// SetAccessToken gets a reference to the given string and assigns it to the AccessToken field.
func (o *TransferToBankRequestAdditionalInfo) SetAccessToken(v string) {
	o.AccessToken = &v
}

func (o TransferToBankRequestAdditionalInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferToBankRequestAdditionalInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fundType"] = o.FundType
	if !utils.IsNil(o.ExternalDivisionId) {
		toSerialize["externalDivisionId"] = o.ExternalDivisionId
	}
	if !utils.IsNil(o.ChargeTarget) {
		toSerialize["chargeTarget"] = o.ChargeTarget
	}
	if !utils.IsNil(o.NeedNotify) {
		toSerialize["needNotify"] = o.NeedNotify
	}
	if !utils.IsNil(o.BeneficiaryAccountName) {
		toSerialize["beneficiaryAccountName"] = o.BeneficiaryAccountName
	}
	if !utils.IsNil(o.AccessToken) {
		toSerialize["accessToken"] = o.AccessToken
	}
	return toSerialize, nil
}

func (o *TransferToBankRequestAdditionalInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fundType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransferToBankRequestAdditionalInfo := _TransferToBankRequestAdditionalInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransferToBankRequestAdditionalInfo)

	if err != nil {
		return err
	}

	*o = TransferToBankRequestAdditionalInfo(varTransferToBankRequestAdditionalInfo)

	return err
}

type NullableTransferToBankRequestAdditionalInfo struct {
	value *TransferToBankRequestAdditionalInfo
	isSet bool
}

func (v NullableTransferToBankRequestAdditionalInfo) Get() *TransferToBankRequestAdditionalInfo {
	return v.value
}

func (v *NullableTransferToBankRequestAdditionalInfo) Set(val *TransferToBankRequestAdditionalInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferToBankRequestAdditionalInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferToBankRequestAdditionalInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferToBankRequestAdditionalInfo(val *TransferToBankRequestAdditionalInfo) *NullableTransferToBankRequestAdditionalInfo {
	return &NullableTransferToBankRequestAdditionalInfo{value: val, isSet: true}
}

func (v NullableTransferToBankRequestAdditionalInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferToBankRequestAdditionalInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


