// Copyright 2025 PT Espay Debit Indonesia Koe
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package disbursement

/*
Disbursement API

API for doing disbursement operations in DANA, including DANA account inquiry, transfer to DANA, and transfer to bank disbursement

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


import (
	"encoding/json"
	"bytes"
	"fmt"
	utils "github.com/dana-id/dana-go/utils"
)

// checks if the BankAccountInquiryRequest type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &BankAccountInquiryRequest{}

// BankAccountInquiryRequest struct for BankAccountInquiryRequest
type BankAccountInquiryRequest struct {
	// Unique transaction identifier on partner system which assigned to each transaction<br> Notes:<br> If the partner receives a timeout or an unexpected response from DANA and partner expects to perform retry request to DANA, please use the partnerReferenceNo that is the same as the one used in the transaction request process before 
	PartnerReferenceNo *string `json:"partnerReferenceNo,omitempty"`
	// Customer account number, in format 628xxx
	CustomerNumber string `json:"customerNumber"`
	// Beneficiary account number
	BeneficiaryAccountNumber string `json:"beneficiaryAccountNumber"`
	// Amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO 
	Amount Money `json:"amount"`
	AdditionalInfo BankAccountInquiryRequestAdditionalInfo `json:"additionalInfo"`
}

type _BankAccountInquiryRequest BankAccountInquiryRequest

// NewBankAccountInquiryRequest instantiates a new BankAccountInquiryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankAccountInquiryRequest(customerNumber string, beneficiaryAccountNumber string, amount Money, additionalInfo BankAccountInquiryRequestAdditionalInfo) *BankAccountInquiryRequest {
	this := BankAccountInquiryRequest{}
	this.CustomerNumber = customerNumber
	this.BeneficiaryAccountNumber = beneficiaryAccountNumber
	this.Amount = amount
	this.AdditionalInfo = additionalInfo
	return &this
}

// NewBankAccountInquiryRequestWithDefaults instantiates a new BankAccountInquiryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankAccountInquiryRequestWithDefaults() *BankAccountInquiryRequest {
	this := BankAccountInquiryRequest{}
	return &this
}

// GetPartnerReferenceNo returns the PartnerReferenceNo field value if set, zero value otherwise.
func (o *BankAccountInquiryRequest) GetPartnerReferenceNo() string {
	if o == nil || utils.IsNil(o.PartnerReferenceNo) {
		var ret string
		return ret
	}
	return *o.PartnerReferenceNo
}

// GetPartnerReferenceNoOk returns a tuple with the PartnerReferenceNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankAccountInquiryRequest) GetPartnerReferenceNoOk() (*string, bool) {
	if o == nil || utils.IsNil(o.PartnerReferenceNo) {
		return nil, false
	}
	return o.PartnerReferenceNo, true
}

// HasPartnerReferenceNo returns a boolean if a field has been set.
func (o *BankAccountInquiryRequest) HasPartnerReferenceNo() bool {
	if o != nil && !utils.IsNil(o.PartnerReferenceNo) {
		return true
	}

	return false
}

// SetPartnerReferenceNo gets a reference to the given string and assigns it to the PartnerReferenceNo field.
func (o *BankAccountInquiryRequest) SetPartnerReferenceNo(v string) {
	o.PartnerReferenceNo = &v
}

// GetCustomerNumber returns the CustomerNumber field value
func (o *BankAccountInquiryRequest) GetCustomerNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerNumber
}

// GetCustomerNumberOk returns a tuple with the CustomerNumber field value
// and a boolean to check if the value has been set.
func (o *BankAccountInquiryRequest) GetCustomerNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerNumber, true
}

// SetCustomerNumber sets field value
func (o *BankAccountInquiryRequest) SetCustomerNumber(v string) {
	o.CustomerNumber = v
}

// GetBeneficiaryAccountNumber returns the BeneficiaryAccountNumber field value
func (o *BankAccountInquiryRequest) GetBeneficiaryAccountNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BeneficiaryAccountNumber
}

// GetBeneficiaryAccountNumberOk returns a tuple with the BeneficiaryAccountNumber field value
// and a boolean to check if the value has been set.
func (o *BankAccountInquiryRequest) GetBeneficiaryAccountNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BeneficiaryAccountNumber, true
}

// SetBeneficiaryAccountNumber sets field value
func (o *BankAccountInquiryRequest) SetBeneficiaryAccountNumber(v string) {
	o.BeneficiaryAccountNumber = v
}

// GetAmount returns the Amount field value
func (o *BankAccountInquiryRequest) GetAmount() Money {
	if o == nil {
		var ret Money
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *BankAccountInquiryRequest) GetAmountOk() (*Money, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *BankAccountInquiryRequest) SetAmount(v Money) {
	o.Amount = v
}

// GetAdditionalInfo returns the AdditionalInfo field value
func (o *BankAccountInquiryRequest) GetAdditionalInfo() BankAccountInquiryRequestAdditionalInfo {
	if o == nil {
		var ret BankAccountInquiryRequestAdditionalInfo
		return ret
	}

	return o.AdditionalInfo
}

// GetAdditionalInfoOk returns a tuple with the AdditionalInfo field value
// and a boolean to check if the value has been set.
func (o *BankAccountInquiryRequest) GetAdditionalInfoOk() (*BankAccountInquiryRequestAdditionalInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdditionalInfo, true
}

// SetAdditionalInfo sets field value
func (o *BankAccountInquiryRequest) SetAdditionalInfo(v BankAccountInquiryRequestAdditionalInfo) {
	o.AdditionalInfo = v
}

func (o BankAccountInquiryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BankAccountInquiryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.PartnerReferenceNo) {
		toSerialize["partnerReferenceNo"] = o.PartnerReferenceNo
	}
	toSerialize["customerNumber"] = o.CustomerNumber
	toSerialize["beneficiaryAccountNumber"] = o.BeneficiaryAccountNumber
	toSerialize["amount"] = o.Amount
	toSerialize["additionalInfo"] = o.AdditionalInfo
	return toSerialize, nil
}

func (o *BankAccountInquiryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customerNumber",
		"beneficiaryAccountNumber",
		"amount",
		"additionalInfo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBankAccountInquiryRequest := _BankAccountInquiryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBankAccountInquiryRequest)

	if err != nil {
		return err
	}

	*o = BankAccountInquiryRequest(varBankAccountInquiryRequest)

	return err
}

type NullableBankAccountInquiryRequest struct {
	value *BankAccountInquiryRequest
	isSet bool
}

func (v NullableBankAccountInquiryRequest) Get() *BankAccountInquiryRequest {
	return v.value
}

func (v *NullableBankAccountInquiryRequest) Set(val *BankAccountInquiryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBankAccountInquiryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBankAccountInquiryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankAccountInquiryRequest(val *BankAccountInquiryRequest) *NullableBankAccountInquiryRequest {
	return &NullableBankAccountInquiryRequest{value: val, isSet: true}
}

func (v NullableBankAccountInquiryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankAccountInquiryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


